insert into city(id, name) values(-10, 'name1')
insert into district(id, name, city_id) values (-111, 'd1', -10)
insert into district(id, name, city_id) values (-112, 'd2', -10)
insert into city(id, name) values(-9, 'name2')
insert into district(id, name, city_id) values (-113, 'd1', -9)
insert into district(id, name, city_id) values (-114, 'd2', -9)
insert into city(id, name) values(-8, 'name3')
insert into district(id, name, city_id) values (-115, 'd1', -8)
insert into district(id, name, city_id) values (-116, 'd2', -8)
insert into city(id, name) values(-7, 'name4')
insert into district(id, name, city_id) values (-117, 'd1', -7)
insert into district(id, name, city_id) values (-118, 'd2', -7)
insert into city(id, name) values(-6, 'name5')
insert into district(id, name, city_id) values (-119, 'd1', -6)
insert into district(id, name, city_id) values (-120, 'd2', -6)
insert into city(id, name) values(-5, 'name6')
insert into district(id, name, city_id) values (-121, 'd1', -5)
insert into district(id, name, city_id) values (-122, 'd2', -5)
insert into city(id, name) values(-4, 'name7')
insert into district(id, name, city_id) values (-123, 'd1', -4)
insert into district(id, name, city_id) values (-124, 'd2', -4)
insert into city(id, name) values(-3, 'name8')
insert into district(id, name, city_id) values (-125, 'd1', -3)
insert into district(id, name, city_id) values (-126, 'd2', -3)
insert into city(id, name) values(-2, 'name9')
insert into district(id, name, city_id) values (-127, 'd1', -2)
insert into district(id, name, city_id) values (-128, 'd2', -2)
insert into city(id, name) values(-1, 'name10')
insert into district(id, name, city_id) values (-129, 'd1', -1)
insert into district(id, name, city_id) values (-130, 'd2', -1)