insert into city(id, name) values(1, 'city1')
insert into district(id, name, city_id) values (-111, 'd1', 1)
insert into district(id, name, city_id) values (-112, 'd2', 1)
insert into city(id, name) values(2, 'city2')
insert into district(id, name, city_id) values (-113, 'd3', 2)
insert into district(id, name, city_id) values (-114, 'd4', 2)
insert into city(id, name) values(3, 'city3')
insert into district(id, name, city_id) values (-115, 'd5', 3)
insert into district(id, name, city_id) values (-116, 'd6', 3)
insert into city(id, name) values(4, 'city4')
insert into district(id, name, city_id) values (-117, 'd7', 4)
insert into district(id, name, city_id) values (-118, 'd8', 4)
insert into city(id, name) values(5, 'city5')
insert into district(id, name, city_id) values (-119, 'd9', 5)
insert into district(id, name, city_id) values (-120, 'd10', 5)